"""updated exercise models

Revision ID: 081a37ffe3c4
Revises: 820e9188fedc
Create Date: 2024-07-25 18:52:04.239398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '081a37ffe3c4'
down_revision: Union[str, None] = '820e9188fedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_category_id'), 'exercise_category', ['id'], unique=False)
    op.create_table('exercise_equipment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_equipment_id'), 'exercise_equipment', ['id'], unique=False)
    op.create_table('exercise_primary_joint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('primary_joint_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_primary_joint_id'), 'exercise_primary_joint', ['id'], unique=False)
    op.create_table('exercise_primary_muscle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('muscle_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_primary_muscle_id'), 'exercise_primary_muscle', ['id'], unique=False)
    op.create_table('exercise_secondary_muscle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('muscle_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_secondary_muscle_id'), 'exercise_secondary_muscle', ['id'], unique=False)
    op.create_table('muscle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('muscle_name', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muscle_id'), 'muscle', ['id'], unique=False)
    op.create_table('primary_joint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('joint_name', sa.String(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_primary_joint_id'), 'primary_joint', ['id'], unique=False)
    op.drop_index('ix_primaryjoint_id', table_name='primaryjoint')
    op.drop_table('primaryjoint')
    op.drop_index('ix_primarymuscle_id', table_name='primarymuscle')
    op.drop_table('primarymuscle')
    op.drop_index('ix_exercisecategory_id', table_name='exercisecategory')
    op.drop_table('exercisecategory')
    op.drop_index('ix_secondarymuscle_id', table_name='secondarymuscle')
    op.drop_table('secondarymuscle')
    op.add_column('equipments', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('equipments', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('equipments', sa.Column('is_deleted', sa.Integer(), nullable=True))
    op.add_column('exercise', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('exercise', sa.Column('rest_between_set', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('exercise', sa.Column('distance', sa.Float(), nullable=True))
    op.add_column('exercise', sa.Column('speed', sa.Float(), nullable=True))
    op.add_column('exercise', sa.Column('video_url_male', sa.String(), nullable=True))
    op.add_column('exercise', sa.Column('video_url_female', sa.String(), nullable=True))
    op.add_column('exercise', sa.Column('thumbnail_male', sa.String(), nullable=True))
    op.add_column('exercise', sa.Column('thumbnail_female', sa.String(), nullable=True))
    op.add_column('exercise', sa.Column('image_url_female', sa.String(), nullable=True))
    op.add_column('exercise', sa.Column('image_url_male', sa.String(), nullable=True))
    op.add_column('exercise', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('exercise', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('exercise', sa.Column('is_deleted', sa.Integer(), nullable=True))
    op.drop_column('exercise', 'thumbnail')
    op.drop_column('exercise', 'exercise_category_id')
    op.drop_column('exercise', 'rest_after_set')
    op.drop_column('exercise', 'equipment_id')
    op.drop_column('exercise', 'primary_muscle_id')
    op.drop_column('exercise', 'video_url')
    op.drop_column('exercise', 'secondary_muscle_id')
    op.drop_column('exercise', 'primary_joint_id')
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('met', 'is_deleted')
    op.drop_column('met', 'updated_by')
    op.drop_column('met', 'created_by')
    op.alter_column('foods', 'weight_unit',
               existing_type=sa.Enum('g', 'ml', 'g_ml', name='weightunitenum'),
               type_=postgresql.ENUM('g', 'ml', 'g_ml', name='_weightunitenum'),
               existing_nullable=True)
    op.alter_column('foods', 'category',
               existing_type=sa.Enum('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='categoryenum'),
               type_=postgresql.ENUM('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='_categoryenum'),
               existing_nullable=True)
    op.add_column('exercise', sa.Column('primary_joint_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercise', sa.Column('secondary_muscle_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercise', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('exercise', sa.Column('primary_muscle_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercise', sa.Column('equipment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercise', sa.Column('rest_after_set', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('exercise', sa.Column('exercise_category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('exercise', sa.Column('thumbnail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('exercise', 'is_deleted')
    op.drop_column('exercise', 'updated_by')
    op.drop_column('exercise', 'created_by')
    op.drop_column('exercise', 'image_url_male')
    op.drop_column('exercise', 'image_url_female')
    op.drop_column('exercise', 'thumbnail_female')
    op.drop_column('exercise', 'thumbnail_male')
    op.drop_column('exercise', 'video_url_female')
    op.drop_column('exercise', 'video_url_male')
    op.drop_column('exercise', 'speed')
    op.drop_column('exercise', 'distance')
    op.drop_column('exercise', 'rest_between_set')
    op.drop_column('exercise', 'category_id')
    op.drop_column('equipments', 'is_deleted')
    op.drop_column('equipments', 'updated_by')
    op.drop_column('equipments', 'created_by')
    op.create_table('secondarymuscle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('muscle_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='secondarymuscle_pkey')
    )
    op.create_index('ix_secondarymuscle_id', 'secondarymuscle', ['id'], unique=False)
    op.create_table('exercisecategory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='exercisecategory_pkey')
    )
    op.create_index('ix_exercisecategory_id', 'exercisecategory', ['id'], unique=False)
    op.create_table('primarymuscle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('muscle_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='primarymuscle_pkey')
    )
    op.create_index('ix_primarymuscle_id', 'primarymuscle', ['id'], unique=False)
    op.create_table('primaryjoint',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('joint_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='primaryjoint_pkey')
    )
    op.create_index('ix_primaryjoint_id', 'primaryjoint', ['id'], unique=False)
    op.drop_index(op.f('ix_primary_joint_id'), table_name='primary_joint')
    op.drop_table('primary_joint')
    op.drop_index(op.f('ix_muscle_id'), table_name='muscle')
    op.drop_table('muscle')
    op.drop_index(op.f('ix_exercise_secondary_muscle_id'), table_name='exercise_secondary_muscle')
    op.drop_table('exercise_secondary_muscle')
    op.drop_index(op.f('ix_exercise_primary_muscle_id'), table_name='exercise_primary_muscle')
    op.drop_table('exercise_primary_muscle')
    op.drop_index(op.f('ix_exercise_primary_joint_id'), table_name='exercise_primary_joint')
    op.drop_table('exercise_primary_joint')
    op.drop_index(op.f('ix_exercise_equipment_id'), table_name='exercise_equipment')
    op.drop_table('exercise_equipment')
    op.drop_index(op.f('ix_exercise_category_id'), table_name='exercise_category')
    op.drop_table('exercise_category')
    # ### end Alembic commands ###
