"""Updated Coach Model

Revision ID: 0cd942ed5af0
Revises: a0dac5ebfcd0
Create Date: 2024-07-23 15:39:46.757757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd942ed5af0'
down_revision: Union[str, None] = 'a0dac5ebfcd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('user_type', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(length=50), nullable=True),
    sa.Column('iban_no', sa.String(length=50), nullable=True),
    sa.Column('acc_holder_name', sa.String(length=50), nullable=True),
    sa.Column('swift_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_detail_id'), 'bank_detail', ['id'], unique=False)
    op.add_column('coach', sa.Column('wallet_address', sa.String(), nullable=True))
    op.add_column('coach', sa.Column('own_coach_id', sa.String(), nullable=True))
    op.add_column('coach', sa.Column('profile_img', sa.String(length=150), nullable=True))
    op.add_column('coach', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('coach', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('coach', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('coach', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('coach', sa.Column('email', sa.String(), nullable=True))
    op.add_column('coach', sa.Column('password', sa.String(length=250), nullable=True))
    op.add_column('coach', sa.Column('phone', sa.String(length=11), nullable=True))
    op.add_column('coach', sa.Column('mobile_number', sa.String(length=11), nullable=True))
    op.add_column('coach', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('coach', sa.Column('source_id', sa.Integer(), nullable=True))
    op.add_column('coach', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('coach', sa.Column('city', sa.String(length=20), nullable=True))
    op.add_column('coach', sa.Column('zipcode', sa.String(length=10), nullable=True))
    op.add_column('coach', sa.Column('address_1', sa.String(length=100), nullable=True))
    op.add_column('coach', sa.Column('address_2', sa.String(length=100), nullable=True))
    op.add_column('coach', sa.Column('coach_since', sa.Date(), nullable=True))
    op.add_column('coach', sa.Column('bank_detail_id', sa.Integer(), nullable=True))
    op.add_column('coach', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('coach', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('coach', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('coach', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'coach', ['email'])
    op.drop_column('coach', 'coach_name')
    op.add_column('coach_organization', sa.Column('coach_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coach_organization', 'coach_status')
    op.add_column('coach', sa.Column('coach_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'coach', type_='unique')
    op.drop_column('coach', 'updated_by')
    op.drop_column('coach', 'created_by')
    op.drop_column('coach', 'updated_at')
    op.drop_column('coach', 'created_at')
    op.drop_column('coach', 'bank_detail_id')
    op.drop_column('coach', 'coach_since')
    op.drop_column('coach', 'address_2')
    op.drop_column('coach', 'address_1')
    op.drop_column('coach', 'zipcode')
    op.drop_column('coach', 'city')
    op.drop_column('coach', 'country_id')
    op.drop_column('coach', 'source_id')
    op.drop_column('coach', 'notes')
    op.drop_column('coach', 'mobile_number')
    op.drop_column('coach', 'phone')
    op.drop_column('coach', 'password')
    op.drop_column('coach', 'email')
    op.drop_column('coach', 'gender')
    op.drop_column('coach', 'dob')
    op.drop_column('coach', 'last_name')
    op.drop_column('coach', 'first_name')
    op.drop_column('coach', 'profile_img')
    op.drop_column('coach', 'own_coach_id')
    op.drop_column('coach', 'wallet_address')
    op.drop_index(op.f('ix_bank_detail_id'), table_name='bank_detail')
    op.drop_table('bank_detail')
    # ### end Alembic commands ###
