"""updated users and clients table

Revision ID: 0dc723c91c29
Revises: 1fcdd41d0859
Create Date: 2024-06-28 12:25:45.784310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dc723c91c29'
down_revision: Union[str, None] = '1fcdd41d0859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recurrency', sa.Enum('daily', 'weekly', 'yearly', 'monthly', name='recurrencyenum'), nullable=True),
    sa.Column('link', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('credit_type', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'inprogress', 'completed', name='statusenum'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.add_column('client_organization', sa.Column('client_status', sa.String(length=100), nullable=True))
    op.add_column('staff', sa.Column('name', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('staff', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('staff', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('staff', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.drop_column('staff', 'date_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('staff', 'updated_by')
    op.drop_column('staff', 'created_by')
    op.drop_column('staff', 'updated_at')
    op.drop_column('staff', 'created_at')
    op.drop_column('staff', 'gender')
    op.drop_column('staff', 'name')
    op.drop_column('client_organization', 'client_status')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
