"""Staff table changes

Revision ID: 0e0f7132bc5e
Revises: 68891312562b
Create Date: 2024-08-19 15:27:39.925764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0f7132bc5e'
down_revision: Union[str, None] = '68891312562b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'client_since',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'client_since',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
