"""New Client edit

Revision ID: 1d8bd06a9b9b
Revises: f0a7fb3f2910
Create Date: 2024-06-27 12:37:30.697971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8bd06a9b9b'
down_revision: Union[str, None] = 'f0a7fb3f2910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint('client_email_address_key', 'client', type_='unique')
    op.create_unique_constraint(None, 'client', ['email'])
    op.drop_column('client', 'email_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'client', type_='unique')
    op.create_unique_constraint('client_email_address_key', 'client', ['email_address'])
    op.drop_column('client', 'email')
    # ### end Alembic commands ###
