"""update relationships in workout table

Revision ID: 1e183eb827e7
Revises: fc291c325f91
Create Date: 2024-08-26 16:08:21.020572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e183eb827e7'
down_revision: Union[str, None] = 'fc291c325f91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_day_exercise', 'intensity_type',
               existing_type=postgresql.ENUM('irm', 'max_intensity', name='intensity'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_day_exercise', 'intensity_type',
               existing_type=postgresql.ENUM('irm', 'max_intensity', name='intensity'),
               nullable=True)
    # ### end Alembic commands ###
