"""updated leads table

Revision ID: 1fcdd41d0859
Revises: ee5e343253ca
Create Date: 2024-06-27 21:55:09.934279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fcdd41d0859'
down_revision: Union[str, None] = 'ee5e343253ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('org_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'org_id')
    # ### end Alembic commands ###
