"""Model table changes make name

Revision ID: 228aaf02755a
Revises: 4d60afe6a350
Create Date: 2024-07-30 16:48:01.910619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228aaf02755a'
down_revision: Union[str, None] = '4d60afe6a350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exercise_exercise_name_key', 'exercise', type_='unique')
    op.drop_constraint('facility_name_key', 'facility', type_='unique')
    op.drop_constraint('income_category_name_key', 'income_category', type_='unique')
    op.drop_constraint('meal_plan_name_key', 'meal_plan', type_='unique')
    op.drop_constraint('membership_group_name_key', 'membership_group', type_='unique')
    op.drop_constraint('membership_plan_name_key', 'membership_plan', type_='unique')
    op.drop_constraint('sale_tax_name_key', 'sale_tax', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('sale_tax_name_key', 'sale_tax', ['name'])
    op.create_unique_constraint('membership_plan_name_key', 'membership_plan', ['name'])
    op.create_unique_constraint('membership_group_name_key', 'membership_group', ['name'])
    op.create_unique_constraint('meal_plan_name_key', 'meal_plan', ['name'])
    op.create_unique_constraint('income_category_name_key', 'income_category', ['name'])
    op.create_unique_constraint('facility_name_key', 'facility', ['name'])
    op.create_unique_constraint('exercise_exercise_name_key', 'exercise', ['exercise_name'])
    # ### end Alembic commands ###
