"""client_membership changes  table changes

Revision ID: 27fba6042a16
Revises: 3b9538866c9d
Create Date: 2024-07-19 17:34:16.667621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27fba6042a16'
down_revision: Union[str, None] = '3b9538866c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_membership', sa.Column('prolongation_period', sa.Integer(), nullable=True))
    op.add_column('client_membership', sa.Column('auto_renew_days', sa.Integer(), nullable=True))
    op.add_column('client_membership', sa.Column('inv_days_cycle', sa.Integer(), nullable=True))
    op.add_column('client_membership', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('client_membership', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('client_membership', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('client_membership', sa.Column('updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_membership', 'updated_by')
    op.drop_column('client_membership', 'created_by')
    op.drop_column('client_membership', 'updated_at')
    op.drop_column('client_membership', 'created_at')
    op.drop_column('client_membership', 'inv_days_cycle')
    op.drop_column('client_membership', 'auto_renew_days')
    op.drop_column('client_membership', 'prolongation_period')
    # ### end Alembic commands ###
