"""User Col Add Test Migrate

Revision ID: 2819a305cb61
Revises: 578c6ac55907
Create Date: 2024-06-26 13:21:07.096571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2819a305cb61'
down_revision: Union[str, None] = '578c6ac55907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_users', 'is_deleted')
    # ### end Alembic commands ###
