"""adding is_root again

Revision ID: 2846086649db
Revises: 2dc4fbf3c396
Create Date: 2024-08-02 15:44:03.107574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2846086649db'
down_revision: Union[str, None] = '2dc4fbf3c396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foods', 'category',
               existing_type=postgresql.ENUM('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='categoryenum'),
               type_=sa.Enum('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='__categoryenum'),
               existing_nullable=True)
    op.alter_column('foods', 'weight_unit',
               existing_type=postgresql.ENUM('g', 'ml', 'g_ml', name='weightunitenum'),
               type_=sa.Enum('g', 'ml', 'g_ml', name='__weightunitenum'),
               existing_nullable=True)
    op.add_column('resource', sa.Column('is_root', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'is_root')
    op.alter_column('foods', 'weight_unit',
               existing_type=sa.Enum('g', 'ml', 'g_ml', name='__weightunitenum'),
               type_=postgresql.ENUM('g', 'ml', 'g_ml', name='weightunitenum'),
               existing_nullable=True)
    op.alter_column('foods', 'category',
               existing_type=sa.Enum('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='__categoryenum'),
               type_=postgresql.ENUM('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='categoryenum'),
               existing_nullable=True)
    # ### end Alembic commands ###
