"""update: resource and role

Revision ID: 2976176f4b31
Revises: 41fed8fe2a21
Create Date: 2024-07-23 13:18:56.340534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2976176f4b31'
down_revision: Union[str, None] = '41fed8fe2a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('link', sa.String(length=50), nullable=True))
    op.add_column('resource', sa.Column('icon', sa.String(length=50), nullable=True))
    op.add_column('role', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'status')
    op.drop_column('resource', 'icon')
    op.drop_column('resource', 'link')
    # ### end Alembic commands ###
