"""workout visisble for and user type

Revision ID: 2bcc41efef28
Revises: 2846086649db
Create Date: 2024-08-04 00:07:47.754599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bcc41efef28'
down_revision: Union[str, None] = '2846086649db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    usertype = sa.Enum('staff', 'member', 'coach', name="usertype")
    usertype.create(op.get_bind())
    op.add_column('workout', sa.Column('visible_for', sa.Enum('only_myself', 'staff_of_my_club', 'members_of_my_club', 'everyone_in_my_club', name='visiblefor'), nullable=False))
    op.add_column('workout', sa.Column('create_user_type', usertype, nullable=False))
    op.add_column('workout', sa.Column('update_user_type', usertype, nullable=True))
    op.add_column('workout_day', sa.Column('create_user_type', usertype, nullable=False))
    op.add_column('workout_day', sa.Column('update_user_type', usertype, nullable=True))
    op.add_column('workout_day_exercise', sa.Column('create_user_type', usertype, nullable=False))
    op.add_column('workout_day_exercise', sa.Column('update_user_type', usertype, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_day_exercise', 'update_user_type')
    op.drop_column('workout_day_exercise', 'create_user_type')
    op.drop_column('workout_day', 'update_user_type')
    op.drop_column('workout_day', 'create_user_type')
    op.drop_column('workout', 'update_user_type')
    op.drop_column('workout', 'create_user_type')
    op.drop_column('workout', 'visible_for')
    # ### end Alembic commands ###
