"""Facilty table changes

Revision ID: 2dc4fbf3c396
Revises: 8a6e4d3fc549
Create Date: 2024-08-02 11:45:38.624039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc4fbf3c396'
down_revision: Union[str, None] = '8a6e4d3fc549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the ENUM types
category_enum = sa.Enum('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='__categoryenum')
weight_unit_enum = sa.Enum('g', 'ml', 'g_ml', name='__weightunitenum')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    category_enum.create(op.get_bind(), checkfirst=True)
    weight_unit_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('foods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('category', category_enum, nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('other_name', sa.String(), nullable=True),
    sa.Column('total_nutrition', sa.Float(), nullable=True),
    sa.Column('kcal', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('carbohydrates', sa.Float(), nullable=True),
    sa.Column('carbs_sugar', sa.Float(), nullable=True),
    sa.Column('carbs_saturated', sa.Float(), nullable=True),
    sa.Column('kilojoules', sa.Float(), nullable=True),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('calcium', sa.Float(), nullable=True),
    sa.Column('iron', sa.Float(), nullable=True),
    sa.Column('magnesium', sa.Float(), nullable=True),
    sa.Column('phosphorus', sa.Float(), nullable=True),
    sa.Column('potassium', sa.Float(), nullable=True),
    sa.Column('sodium', sa.Float(), nullable=True),
    sa.Column('zinc', sa.Float(), nullable=True),
    sa.Column('copper', sa.Float(), nullable=True),
    sa.Column('selenium', sa.Float(), nullable=True),
    sa.Column('vitamin_a', sa.Float(), nullable=True),
    sa.Column('vitamin_b1', sa.Float(), nullable=True),
    sa.Column('vitamin_b2', sa.Float(), nullable=True),
    sa.Column('vitamin_b6', sa.Float(), nullable=True),
    sa.Column('vitamin_b12', sa.Float(), nullable=True),
    sa.Column('vitamin_c', sa.Float(), nullable=True),
    sa.Column('vitamin_d', sa.Float(), nullable=True),
    sa.Column('vitamin_e', sa.Float(), nullable=True),
    sa.Column('folic_acid', sa.Float(), nullable=True),
    sa.Column('fat_unsaturated', sa.Float(), nullable=True),
    sa.Column('cholesterol', sa.Float(), nullable=True),
    sa.Column('alcohol', sa.Float(), nullable=True),
    sa.Column('alchohol_mono', sa.Float(), nullable=True),
    sa.Column('alchohol_poly', sa.Float(), nullable=True),
    sa.Column('trans_fat', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_unit', weight_unit_enum, nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_id'), 'foods', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_foods_id'), table_name='foods')
    op.drop_table('foods')
    category_enum.drop(op.get_bind())
    weight_unit_enum.drop(op.get_bind())
    # ### end Alembic commands ###
