"""is_root in resource

Revision ID: 2f8f7e56afb7
Revises: fc212dd9ccab
Create Date: 2024-08-01 12:50:48.866359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8f7e56afb7'
down_revision: Union[str, None] = 'fc212dd9ccab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('is_root', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'is_root')
    # ### end Alembic commands ###
