"""Facilty table changes

Revision ID: 3b9538866c9d
Revises: d3378231a5b6
Create Date: 2024-07-19 16:01:52.188624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b9538866c9d'
down_revision: Union[str, None] = 'd3378231a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('min_limit', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_id'), 'facility', ['id'], unique=False)
    op.create_table('facility_membership_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('membership_plan_id', sa.Integer(), nullable=True),
    sa.Column('total_credits', sa.Integer(), nullable=True),
    sa.Column('validity', sa.JSON(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_membership_plan_id'), 'facility_membership_plan', ['id'], unique=False)
    op.drop_index('ix_credits_id', table_name='credits')
    op.drop_table('credits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('min_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='credits_pkey')
    )
    op.create_index('ix_credits_id', 'credits', ['id'], unique=False)
    op.drop_index(op.f('ix_facility_membership_plan_id'), table_name='facility_membership_plan')
    op.drop_table('facility_membership_plan')
    op.drop_index(op.f('ix_facility_id'), table_name='facility')
    op.drop_table('facility')
    # ### end Alembic commands ###
