"""Lead Updated

Revision ID: 3ebfc1a5ed4a
Revises: 1d8bd06a9b9b
Create Date: 2024-06-27 14:21:14.642838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ebfc1a5ed4a'
down_revision: Union[str, None] = '1d8bd06a9b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
