"""Staff Table changes

Revision ID: 459713a4043e
Revises: b41f1fc83f97
Create Date: 2024-07-31 17:10:51.970021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '459713a4043e'
down_revision: Union[str, None] = 'b41f1fc83f97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('last_checkin', sa.DateTime(), nullable=True))
    op.add_column('staff', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('staff', sa.Column('mobile_number', sa.String(length=15), nullable=True))
    op.alter_column('staff', 'phone',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.drop_column('staff', 'mobile')
    op.drop_column('staff', 'check_in')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('check_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('staff', sa.Column('mobile', sa.VARCHAR(length=11), autoincrement=False, nullable=True))
    op.alter_column('staff', 'phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.drop_column('staff', 'mobile_number')
    op.drop_column('staff', 'status')
    op.drop_column('staff', 'last_checkin')
    # ### end Alembic commands ###
