"""Test v6

Revision ID: 4c194bf65090
Revises: 1b0fdf1e135a
Create Date: 2024-06-26 16:55:37.967881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c194bf65090'
down_revision: Union[str, None] = '1b0fdf1e135a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('own_mem_id', sa.String(), nullable=False))
    op.drop_column('client', 'own_member_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('own_member_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('client', 'own_mem_id')
    # ### end Alembic commands ###
