"""Model table changes make name uniqe

Revision ID: 4d60afe6a350
Revises: 1981c2d283ba
Create Date: 2024-07-30 13:48:41.943494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d60afe6a350'
down_revision: Union[str, None] = '1981c2d283ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercise', 'difficulty',
               existing_type=postgresql.ENUM('Novice', 'Beginner', 'Intermediate', 'Advance', 'Expert', name='difficulty'),
               nullable=False)
    op.create_unique_constraint(None, 'exercise', ['exercise_name'])
    op.alter_column('facility', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'facility', ['name'])
    op.alter_column('income_category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'income_category', ['name'])
    op.alter_column('meal_plan', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'meal_plan', ['name'])
    op.alter_column('membership_group', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'membership_group', ['name'])
    op.alter_column('membership_plan', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'membership_plan', ['name'])
    op.alter_column('sale_tax', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'sale_tax', ['name'])
    op.add_column('workout', sa.Column('org_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'org_id')
    op.drop_constraint(None, 'sale_tax', type_='unique')
    op.alter_column('sale_tax', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'membership_plan', type_='unique')
    op.alter_column('membership_plan', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'membership_group', type_='unique')
    op.alter_column('membership_group', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'meal_plan', type_='unique')
    op.alter_column('meal_plan', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'income_category', type_='unique')
    op.alter_column('income_category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'facility', type_='unique')
    op.alter_column('facility', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'exercise', type_='unique')
    op.alter_column('exercise', 'difficulty',
               existing_type=postgresql.ENUM('Novice', 'Beginner', 'Intermediate', 'Advance', 'Expert', name='difficulty'),
               nullable=True)
    # ### end Alembic commands ###
