"""member and coach changes

Revision ID: 56921b0fd505
Revises: 20aac64398d5
Create Date: 2024-08-29 12:39:50.046149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56921b0fd505'
down_revision: Union[str, None] = '20aac64398d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_membership', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('coach_organization', sa.Column('activated_on', sa.Date(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('coach_organization', 'activated_on')
    op.drop_column('client_membership', 'org_id')
    # ### end Alembic commands ###
