"""Add Status in Credits

Revision ID: 5765d4d376fe
Revises: 4da1729a1b8a
Create Date: 2024-07-06 13:41:46.642583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5765d4d376fe'
down_revision: Union[str, None] = '4da1729a1b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credits', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credits', 'status')
    # ### end Alembic commands ###
