"""Add Exersice Tables

Revision ID: 5f82b3571275
Revises: 7daf1d5fe300
Create Date: 2024-07-02 15:04:02.698307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f82b3571275'
down_revision: Union[str, None] = '7daf1d5fe300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipments_id'), 'equipments', ['id'], unique=False)
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_name', sa.String(), nullable=False),
    sa.Column('visible_for', sa.Enum('only_myself', 'staff_of_my_club', 'members_of_my_club', 'everyone_in_my_club', name='visiblefor'), nullable=False),
    sa.Column('exercise_category_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('primary_muscle_id', sa.Integer(), nullable=True),
    sa.Column('secondary_muscle_id', sa.Integer(), nullable=True),
    sa.Column('primary_joint_id', sa.Integer(), nullable=True),
    sa.Column('exercise_type', sa.String(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('seconds_per_set', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('repetitions_per_set', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('rest_after_set', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('met_id', sa.Integer(), nullable=True),
    sa.Column('gif_url', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_id'), 'exercise', ['id'], unique=False)
    op.create_table('exercisecategory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercisecategory_id'), 'exercisecategory', ['id'], unique=False)
    op.create_table('met',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('met_value', sa.Float(), nullable=False),
    sa.Column('met_description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_met_id'), 'met', ['id'], unique=False)
    op.create_table('primaryjoint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('joint_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_primaryjoint_id'), 'primaryjoint', ['id'], unique=False)
    op.create_table('primarymuscle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('muscle_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_primarymuscle_id'), 'primarymuscle', ['id'], unique=False)
    op.create_table('secondarymuscle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('muscle_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secondarymuscle_id'), 'secondarymuscle', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secondarymuscle_id'), table_name='secondarymuscle')
    op.drop_table('secondarymuscle')
    op.drop_index(op.f('ix_primarymuscle_id'), table_name='primarymuscle')
    op.drop_table('primarymuscle')
    op.drop_index(op.f('ix_primaryjoint_id'), table_name='primaryjoint')
    op.drop_table('primaryjoint')
    op.drop_index(op.f('ix_met_id'), table_name='met')
    op.drop_table('met')
    op.drop_index(op.f('ix_exercisecategory_id'), table_name='exercisecategory')
    op.drop_table('exercisecategory')
    op.drop_index(op.f('ix_exercise_id'), table_name='exercise')
    op.drop_table('exercise')
    op.drop_index(op.f('ix_equipments_id'), table_name='equipments')
    op.drop_table('equipments')
    # ### end Alembic commands ###
