"""updated attributes in table

Revision ID: 6a968b2da37b
Revises: 8356593189b3
Create Date: 2024-08-20 14:54:56.820104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a968b2da37b'
down_revision: Union[str, None] = '8356593189b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_coach', 'updated_at')
    op.drop_column('client_coach', 'created_at')
    op.drop_column('client_membership', 'updated_by')
    op.drop_column('client_membership', 'updated_at')
    op.drop_column('client_membership', 'created_at')
    op.drop_column('client_membership', 'created_by')
    op.drop_column('client_organization', 'updated_at')
    op.drop_column('client_organization', 'created_at')
    op.drop_column('exercise_equipment', 'updated_by')
    op.drop_column('exercise_equipment', 'updated_at')
    op.drop_column('exercise_equipment', 'created_at')
    op.drop_column('exercise_equipment', 'created_by')
    op.drop_column('exercise_primary_joint', 'updated_by')
    op.drop_column('exercise_primary_joint', 'updated_at')
    op.drop_column('exercise_primary_joint', 'created_at')
    op.drop_column('exercise_primary_joint', 'created_by')
    op.drop_column('exercise_primary_muscle', 'updated_by')
    op.drop_column('exercise_primary_muscle', 'updated_at')
    op.drop_column('exercise_primary_muscle', 'created_at')
    op.drop_column('exercise_primary_muscle', 'created_by')
    op.drop_column('exercise_secondary_muscle', 'updated_by')
    op.drop_column('exercise_secondary_muscle', 'updated_at')
    op.drop_column('exercise_secondary_muscle', 'created_at')
    op.drop_column('exercise_secondary_muscle', 'created_by')
    op.drop_column('muscle', 'created_at')
    op.drop_column('muscle', 'updated_at')
    op.drop_column('muscle', 'updated_by')
    op.drop_column('muscle', 'created_by')
    op.drop_column('primary_joint', 'created_at')
    op.drop_column('primary_joint', 'updated_at')
    op.drop_column('primary_joint', 'updated_by')
    op.drop_column('primary_joint', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('primary_joint', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('primary_joint', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('primary_joint', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('primary_joint', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('muscle', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('muscle', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('muscle', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('muscle', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('exercise_secondary_muscle', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercise_secondary_muscle', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('exercise_secondary_muscle', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('exercise_secondary_muscle', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercise_primary_muscle', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercise_primary_muscle', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('exercise_primary_muscle', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('exercise_primary_muscle', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercise_primary_joint', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercise_primary_joint', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('exercise_primary_joint', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('exercise_primary_joint', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercise_equipment', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercise_equipment', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('exercise_equipment', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('exercise_equipment', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('client_organization', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('client_organization', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('client_membership', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('client_membership', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('client_membership', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('client_membership', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('client_coach', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('client_coach', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
