"""Event table update

Revision ID: 6ec264827316
Revises: 0dc723c91c29
Create Date: 2024-06-28 16:52:43.073451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec264827316'
down_revision: Union[str, None] = '0dc723c91c29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('participants', sa.String(length=100), nullable=True))
    op.alter_column('events', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('events', 'email')
    op.drop_column('events', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('events', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('events', 'participants')
    # ### end Alembic commands ###
