"""Test v7

Revision ID: 70c9351dfca6
Revises: 4c194bf65090
Create Date: 2024-06-26 17:19:33.585399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70c9351dfca6'
down_revision: Union[str, None] = '4c194bf65090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('own_member_id', sa.String(), nullable=False))
    op.drop_column('client', 'own_mem_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('own_mem_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('client', 'own_member_id')
    # ### end Alembic commands ###
