"""organization v4 table changes

Revision ID: 71e86f498330
Revises: ad87d765f9eb
Create Date: 2024-08-07 17:31:33.326936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71e86f498330'
down_revision: Union[str, None] = 'ad87d765f9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.add_column('organization', sa.Column('profile_img', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'profile_img')

    # ### end Alembic commands ###
