"""Role Permission Updated

Revision ID: 7286b6f5a166
Revises: 27fba6042a16
Create Date: 2024-07-19 17:56:17.406891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7286b6f5a166'
down_revision: Union[str, None] = '27fba6042a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('access_type', sa.String(length=50), nullable=True))
    op.add_column('permission', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('permission', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('permission', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('permission', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.drop_column('permission', 'access')
    op.add_column('resource', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('resource', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('resource', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('resource', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.drop_column('resource', 'is_parent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('is_parent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('resource', 'updated_by')
    op.drop_column('resource', 'created_by')
    op.drop_column('resource', 'updated_at')
    op.drop_column('resource', 'created_at')
    op.add_column('permission', sa.Column('access', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('permission', 'updated_by')
    op.drop_column('permission', 'created_by')
    op.drop_column('permission', 'updated_at')
    op.drop_column('permission', 'created_at')
    op.drop_column('permission', 'access_type')
    # ### end Alembic commands ###
