"""update food table: column brand

Revision ID: 72c452d6b53d
Revises: fb25f775b0ad
Create Date: 2024-07-24 13:19:18.515781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c452d6b53d'
down_revision: Union[str, None] = 'fb25f775b0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('brand', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'brand')
    # ### end Alembic commands ###
