"""membership status

Revision ID: 73843c28b434
Revises: b3710ebde92c
Create Date: 2024-08-07 12:45:56.610280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73843c28b434'
down_revision: Union[str, None] = 'b3710ebde92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    membership_status = sa.Enum('active', 'inactive', name='membershipstatus')
    membership_status.create(op.get_bind(), checkfirst=True)
    op.alter_column('facility', 'status',
               existing_type=postgresql.ENUM('new', 'contacted', 'incontact', 'appointment_made', 'appointment_held', 'free_trail', 'signup_scheduled', 'no_show', 'closed_refused', 'closed_lost_contact', 'closed_disqualified', 'closed_third_party_aggregators', name='status'),
               type_=sa.Enum('active', 'inactive', name='membershipstatus'),
               existing_nullable=False,
               postgresql_using="status::text::membershipstatus")
    op.alter_column('income_category', 'status',
               existing_type=postgresql.ENUM('new', 'contacted', 'incontact', 'appointment_made', 'appointment_held', 'free_trail', 'signup_scheduled', 'no_show', 'closed_refused', 'closed_lost_contact', 'closed_disqualified', 'closed_third_party_aggregators', name='status'),
               type_=sa.Enum('active', 'inactive', name='membershipstatus'),
               existing_nullable=False,
               postgresql_using="status::text::membershipstatus")
    op.alter_column('membership_plan', 'status',
               existing_type=postgresql.ENUM('new', 'contacted', 'incontact', 'appointment_made', 'appointment_held', 'free_trail', 'signup_scheduled', 'no_show', 'closed_refused', 'closed_lost_contact', 'closed_disqualified', 'closed_third_party_aggregators', name='status'),
               type_=sa.Enum('active', 'inactive', name='membershipstatus'),
               existing_nullable=True,
               postgresql_using="status::text::membershipstatus")
    op.alter_column('sale_tax', 'status',
               existing_type=postgresql.ENUM('new', 'contacted', 'incontact', 'appointment_made', 'appointment_held', 'free_trail', 'signup_scheduled', 'no_show', 'closed_refused', 'closed_lost_contact', 'closed_disqualified', 'closed_third_party_aggregators', name='status'),
               type_=sa.Enum('active', 'inactive', name='membershipstatus'),
               existing_nullable=False,
               postgresql_using="status::text::membershipstatus")
    #op.alter_column('workout', 'updated_at',
    #           existing_type=postgresql.TIMESTAMP(),
    #           nullable=False)
    #op.alter_column('workout_day', 'create_user_type',
    #           existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
    #           nullable=False)
    #op.alter_column('workout_day', 'updated_at',
    #           existing_type=postgresql.TIMESTAMP(),
    #           nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('workout_day', 'updated_at',
    #           existing_type=postgresql.TIMESTAMP(),
    #           nullable=True)
    #op.alter_column('workout_day', 'create_user_type',
    #           existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
    #           nullable=True)
    #op.alter_column('workout', 'updated_at',
    #           existing_type=postgresql.TIMESTAMP(),
    #           nullable=True)
    op.alter_column('sale_tax', 'status',
               existing_type=sa.Enum('active', 'inactive', name='membershipstatus'),
               type_=postgresql.ENUM('new', 'contacted', 'incontact', 'appointment_made', 'appointment_held', 'free_trail', 'signup_scheduled', 'no_show', 'closed_refused', 'closed_lost_contact', 'closed_disqualified', 'closed_third_party_aggregators', name='status'),
               existing_nullable=False)
    op.alter_column('membership_plan', 'status',
               existing_type=sa.Enum('active', 'inactive', name='membershipstatus'),
               type_=postgresql.ENUM('new', 'contacted', 'incontact', 'appointment_made', 'appointment_held', 'free_trail', 'signup_scheduled', 'no_show', 'closed_refused', 'closed_lost_contact', 'closed_disqualified', 'closed_third_party_aggregators', name='status'),
               existing_nullable=True)
    op.alter_column('income_category', 'status',
               existing_type=sa.Enum('active', 'inactive', name='membershipstatus'),
               type_=postgresql.ENUM('new', 'contacted', 'incontact', 'appointment_made', 'appointment_held', 'free_trail', 'signup_scheduled', 'no_show', 'closed_refused', 'closed_lost_contact', 'closed_disqualified', 'closed_third_party_aggregators', name='status'),
               existing_nullable=False)
    op.alter_column('facility', 'status',
               existing_type=sa.Enum('active', 'inactive', name='membershipstatus'),
               type_=postgresql.ENUM('new', 'contacted', 'incontact', 'appointment_made', 'appointment_held', 'free_trail', 'signup_scheduled', 'no_show', 'closed_refused', 'closed_lost_contact', 'closed_disqualified', 'closed_third_party_aggregators', name='status'),
               existing_nullable=False)
    #op.drop_index(op.f('ix_member_workout_id'), table_name='member_workout')
    #op.drop_table('member_workout')
    # ### end Alembic commands ###
