""" enum for membership  

Revision ID: 7a9da3441dd4
Revises: e6331b9cc6e6
Create Date: 2024-08-08 16:45:38.476043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a9da3441dd4'
down_revision: Union[str, None] = 'e6331b9cc6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'business_type',
               existing_type=postgresql.ENUM('bootcamp', 'community_services', 'corporate_health', 'crossfit_box', 'dance_studio', 'dietitian', 'educational_institute', 'fitness_center', 'hospital_clinic', 'lifestyle_coach', 'martial_arts_center', 'online_coach', 'personal_trainer', 'personal_training_studio', 'physiotherapy_clinic', 'yoga_pilates_studio', 'other', name='businesstypeenum'),
               type_=sa.String(length=150),
               existing_nullable=True)
     # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.alter_column('organization', 'business_type',
               existing_type=sa.String(length=150),
               type_=postgresql.ENUM('bootcamp', 'community_services', 'corporate_health', 'crossfit_box', 'dance_studio', 'dietitian', 'educational_institute', 'fitness_center', 'hospital_clinic', 'lifestyle_coach', 'martial_arts_center', 'online_coach', 'personal_trainer', 'personal_training_studio', 'physiotherapy_clinic', 'yoga_pilates_studio', 'other', name='businesstypeenum'),
               existing_nullable=True)
    # ### end Alembic commands ###
