"""Coach ERD changes s

Revision ID: 820e9188fedc
Revises: a13a56272730
Create Date: 2024-07-24 14:09:39.696594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '820e9188fedc'
down_revision: Union[str, None] = 'a13a56272730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coach', 'coach_since',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('coach_organization', 'coach_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('foods', 'weight_unit',
               existing_type=sa.Enum('g', 'ml', 'g_ml', name='weightunitenum'),
               type_=postgresql.ENUM('g', 'ml', 'g_ml', name='_weightunitenum'),
               existing_nullable=True)
    op.alter_column('foods', 'category',
               existing_type=sa.Enum('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='categoryenum'),
               type_=postgresql.ENUM('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='_categoryenum'),
               existing_nullable=True)
    op.alter_column('coach_organization', 'coach_status',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('coach', 'coach_since',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
