"""meal plan enum revised

Revision ID: 8356593189b3
Revises: e2ba705de480
Create Date: 2024-08-20 13:43:03.492555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8356593189b3'
down_revision: Union[str, None] = 'e2ba705de480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

new_mealtime_enum = postgresql.ENUM(
    'breakfast', 'morning_snack', 'lunch', 'afternoon_snack', 'dinner', 'evening_snack',
    name='mealtimeenum'
)
def upgrade() -> None:
    op.execute("DROP TYPE IF EXISTS mealtimeenum cascade")
    new_mealtime_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('meal', sa.Column('meal_time', new_mealtime_enum, nullable=True))
    



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
