"""Model email make unrequired

Revision ID: 8a6e4d3fc549
Revises: 2f8f7e56afb7
Create Date: 2024-08-01 18:20:50.526946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a6e4d3fc549'
down_revision: Union[str, None] = '2f8f7e56afb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_email_key', 'client', type_='unique')
    op.drop_constraint('coach_email_key', 'coach', type_='unique')
    op.drop_column('resource', 'is_root')
    op.drop_index('ix_staff_email', table_name='staff')
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.create_index('ix_staff_email', 'staff', ['email'], unique=True)
    op.add_column('resource', sa.Column('is_root', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_unique_constraint('coach_email_key', 'coach', ['email'])
    op.create_unique_constraint('client_email_key', 'client', ['email'])
    # ### end Alembic commands ###
