"""updated fields in exercise

Revision ID: 8dd73e104156
Revises: 9d4544c898ed
Create Date: 2024-08-22 14:10:29.683791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd73e104156'
down_revision: Union[str, None] = '9d4544c898ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('created_by_type', sa.String(), nullable=True))
    op.add_column('exercise', sa.Column('updated_by_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'updated_by_type')
    op.drop_column('exercise', 'created_by_type')
    # ### end Alembic commands ###
