"""updated staff table

Revision ID: 9167b08b6f89
Revises: 8dd73e104156
Create Date: 2024-08-22 14:17:37.157820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9167b08b6f89'
down_revision: Union[str, None] = '8dd73e104156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('reset_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'reset_token')
    # ### end Alembic commands ###
