"""updated meal plan

Revision ID: 9d4544c898ed
Revises: fc667d552c48
Create Date: 2024-08-21 16:59:13.935925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d4544c898ed'
down_revision: Union[str, None] = 'fc667d552c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'updated_by')
    op.drop_column('meal', 'updated_at')
    op.drop_column('meal', 'created_by')
    op.drop_column('meal', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('meal', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('meal', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('meal', sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
