"""update: resource parent

Revision ID: a0dac5ebfcd0
Revises: 2976176f4b31
Create Date: 2024-07-23 14:06:07.676428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0dac5ebfcd0'
down_revision: Union[str, None] = '2976176f4b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('is_parent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'is_parent')
    # ### end Alembic commands ###
