"""client table changes

Revision ID: ad5e939b994e
Revises: 0bfd9556fbbe
Create Date: 2024-07-29 16:49:01.744758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5e939b994e'
down_revision: Union[str, None] = '0bfd9556fbbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('client', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('client', sa.Column('bmi', sa.Float(), nullable=True))
    op.add_column('client', sa.Column('circumference_waist_navel', sa.Float(), nullable=True))
    op.add_column('client', sa.Column('fat_percentage', sa.Float(), nullable=True))
    op.add_column('client', sa.Column('muscle_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'muscle_percentage')
    op.drop_column('client', 'fat_percentage')
    op.drop_column('client', 'circumference_waist_navel')
    op.drop_column('client', 'bmi')
    op.drop_column('client', 'weight')
    op.drop_column('client', 'height')
    # ### end Alembic commands ###
