"""Changed Attributes In Meal Plan

Revision ID: adaaacffcfa2
Revises: 0e0f7132bc5e
Create Date: 2024-08-19 17:26:37.393437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adaaacffcfa2'
down_revision: Union[str, None] = '0e0f7132bc5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('is_validated', sa.Boolean(), nullable=True))
    op.alter_column('meal', 'meal_time',
               existing_type=postgresql.ENUM('breakfast', 'breakfast_snack', 'lunch', 'lunch_snack', 'dinner', 'dinner_snack', name='mealtimeenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal', 'meal_time',
               existing_type=postgresql.ENUM('breakfast', 'breakfast_snack', 'lunch', 'lunch_snack', 'dinner', 'dinner_snack', name='mealtimeenum'),
               nullable=False)
    op.drop_column('foods', 'is_validated')
    # ### end Alembic commands ###
