"""Update user table with activate on and checking time at staff 

Revision ID: b21fe957ee9f
Revises: f60c0daa7703
Create Date: 2024-07-03 17:49:26.085064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21fe957ee9f'
down_revision: Union[str, None] = 'f60c0daa7703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('activated_on', sa.Date(), nullable=True))
    op.add_column('staff', sa.Column('check_in', sa.DateTime(), nullable=True))
    op.add_column('staff', sa.Column('last_online', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'last_online')
    op.drop_column('staff', 'check_in')
    op.drop_column('staff', 'activated_on')
    # ### end Alembic commands ###
