"""workout member assing to3

Revision ID: b3710ebde92c
Revises: e555d6176d9d
Create Date: 2024-08-07 09:25:08.106507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3710ebde92c'
down_revision: Union[str, None] = 'e555d6176d9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    client_status = sa.Enum('active', 'inactive', 'pending', name='coachstatus')
    client_status.create(op.get_bind(), checkfirst=True)
    #op.alter_column('coach_organization', 'coach_status',
    #           existing_type=postgresql.ENUM('active', 'inactive', 'pending', name='coach_status'),
    #           type_=sa.Enum('active', 'inactive', 'pending', name='status'),
    #           existing_nullable=True)
    op.execute('ALTER TABLE coach_organization ALTER COLUMN coach_status TYPE coachstatus USING coach_status::text::coachstatus')
    op.alter_column('exercise', 'exercise_intensity',
               existing_type=postgresql.ENUM('irm%', 'max_intensity', name='intensity'),
               nullable=False)
    op.create_index(op.f('ix_exercise_equipment_exercise_id'), 'exercise_equipment', ['exercise_id'], unique=False)
    op.alter_column('facility', 'status',
               existing_type=postgresql.ENUM('new', 'contacted', 'incontact', 'appointment_made', 'appointment_held', 'free_trail', 'signup_scheduled', 'no_show', 'closed_refused', 'closed_lost_contact', 'closed_disqualified', 'closed_third_party_aggregators', name='status'),
               nullable=False)
    categoryenum = sa.Enum('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='categoryenum')
    categoryenum.create(op.get_bind(), checkfirst=True)
    #op.alter_column('foods', 'category',
    #           existing_type=postgresql.ENUM('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='__categoryenum'),
    #           type_=sa.Enum('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='categoryenum'),
    #           existing_nullable=True)
    op.execute('ALTER TABLE foods ALTER COLUMN category TYPE categoryenum USING category::text::categoryenum')
    weightunitenum = sa.Enum('g', 'ml', 'g_ml', name='weightunitenum')
    weightunitenum.create(op.get_bind(), checkfirst=True)
    #op.alter_column('foods', 'weight_unit',
    #           existing_type=postgresql.ENUM('g', 'ml', 'g_ml', name='__weightunitenum'),
    #           type_=sa.Enum('g', 'ml', 'g_ml', name='weightunitenum'),
    #           existing_nullable=True)
    op.execute('ALTER TABLE foods ALTER COLUMN weight_unit TYPE weightunitenum USING weight_unit::text::weightunitenum')
    op.alter_column('income_category', 'status',
               existing_type=postgresql.ENUM('new', 'contacted', 'incontact', 'appointment_made', 'appointment_held', 'free_trail', 'signup_scheduled', 'no_show', 'closed_refused', 'closed_lost_contact', 'closed_disqualified', 'closed_third_party_aggregators', name='status'),
               nullable=False)
    op.alter_column('sale_tax', 'status',
               existing_type=postgresql.ENUM('new', 'contacted', 'incontact', 'appointment_made', 'appointment_held', 'free_trail', 'signup_scheduled', 'no_show', 'closed_refused', 'closed_lost_contact', 'closed_disqualified', 'closed_third_party_aggregators', name='status'),
               nullable=False)
    staff_status = sa.Enum('active', 'inactive', 'pending', name='staffstatus')
    staff_status.create(op.get_bind(), checkfirst=True)
    #op.alter_column('staff', 'status',
    #           existing_type=postgresql.ENUM('active', 'inactive', 'pending', name='coach_status'),
    #           type_=sa.Enum('active', 'inactive', 'pending', name='status'),
    #           existing_nullable=True)
    op.execute('ALTER TABLE staff ALTER COLUMN status TYPE staffstatus USING status::text::staffstatus')
    op.alter_column('workout', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=False)
    op.alter_column('workout', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workout', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workout', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('workout_day', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day', 'day_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workout_day', 'week',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day', 'day',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=True)
    op.alter_column('workout_day', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workout_day', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workout_day', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_workout_day_workout_id'), 'workout_day', ['workout_id'], unique=False)
    op.alter_column('workout_day_exercise', 'workout_day_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day_exercise', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day_exercise', 'exercise_type',
               existing_type=postgresql.ENUM('time_based', 'repetition_based', name='exercisetype'),
               nullable=False)
    op.alter_column('workout_day_exercise', 'sets',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day_exercise', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=False)
    op.alter_column('workout_day_exercise', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_workout_day_exercise_exercise_id'), 'workout_day_exercise', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_day_exercise_workout_day_id'), 'workout_day_exercise', ['workout_day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_day_exercise_workout_day_id'), table_name='workout_day_exercise')
    op.drop_index(op.f('ix_workout_day_exercise_exercise_id'), table_name='workout_day_exercise')
    op.alter_column('workout_day_exercise', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day_exercise', 'update_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=True)
    op.alter_column('workout_day_exercise', 'sets',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day_exercise', 'exercise_type',
               existing_type=postgresql.ENUM('time_based', 'repetition_based', name='exercisetype'),
               nullable=True)
    op.alter_column('workout_day_exercise', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day_exercise', 'workout_day_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_workout_day_workout_id'), table_name='workout_day')
    op.alter_column('workout_day', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('workout_day', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workout_day', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day', 'update_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=True)
    op.alter_column('workout_day', 'day',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day', 'week',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day', 'day_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workout_day', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('workout', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workout', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout', 'update_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=True)
    op.alter_column('staff', 'status',
               existing_type=sa.Enum('active', 'inactive', 'pending', name='status'),
               type_=postgresql.ENUM('active', 'inactive', 'pending', name='coach_status'),
               existing_nullable=True)
    op.alter_column('sale_tax', 'status',
               existing_type=postgresql.ENUM('new', 'contacted', 'incontact', 'appointment_made', 'appointment_held', 'free_trail', 'signup_scheduled', 'no_show', 'closed_refused', 'closed_lost_contact', 'closed_disqualified', 'closed_third_party_aggregators', name='status'),
               nullable=True)
    op.alter_column('income_category', 'status',
               existing_type=postgresql.ENUM('new', 'contacted', 'incontact', 'appointment_made', 'appointment_held', 'free_trail', 'signup_scheduled', 'no_show', 'closed_refused', 'closed_lost_contact', 'closed_disqualified', 'closed_third_party_aggregators', name='status'),
               nullable=True)
    op.alter_column('foods', 'weight_unit',
               existing_type=sa.Enum('g', 'ml', 'g_ml', name='weightunitenum'),
               type_=postgresql.ENUM('g', 'ml', 'g_ml', name='__weightunitenum'),
               existing_nullable=True)
    op.alter_column('foods', 'category',
               existing_type=sa.Enum('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='categoryenum'),
               type_=postgresql.ENUM('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='__categoryenum'),
               existing_nullable=True)
    op.alter_column('facility', 'status',
               existing_type=postgresql.ENUM('new', 'contacted', 'incontact', 'appointment_made', 'appointment_held', 'free_trail', 'signup_scheduled', 'no_show', 'closed_refused', 'closed_lost_contact', 'closed_disqualified', 'closed_third_party_aggregators', name='status'),
               nullable=True)
    op.drop_index(op.f('ix_exercise_equipment_exercise_id'), table_name='exercise_equipment')
    op.alter_column('exercise', 'intensity_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('exercise', 'exercise_intensity',
               existing_type=postgresql.ENUM('irm%', 'max_intensity', name='intensity'),
               nullable=True)
    op.alter_column('coach_organization', 'coach_status',
               existing_type=sa.Enum('active', 'inactive', 'pending', name='status'),
               type_=postgresql.ENUM('active', 'inactive', 'pending', name='coach_status'),
               existing_nullable=True)
    # ### end Alembic commands ###
