"""Meal Plan changes

Revision ID: b41f1fc83f97
Revises: 228aaf02755a
Create Date: 2024-07-30 16:57:06.565925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41f1fc83f97'
down_revision: Union[str, None] = '228aaf02755a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal_plan', sa.Column('org_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plan', 'org_id')
    # ### end Alembic commands ###
