"""API status update

Revision ID: c4441fabf66f
Revises: 73843c28b434
Create Date: 2024-08-07 14:49:46.063883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4441fabf66f'
down_revision: Union[str, None] = '73843c28b434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    rolestatus = sa.Enum('active','inactive',name="rolestatus")
    rolestatus.create(op.get_bind())
    
    op.drop_index('ix_exercise_equipment_exercise_id', table_name='exercise_equipment')
    op.alter_column('role', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.Enum('active', 'inactive', name='rolestatus'),
               existing_nullable=True,
               postgresql_using="status::text::rolestatus")
    op.alter_column('workout', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workout_day', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day', 'day_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workout_day', 'week',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day', 'day',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=False)
    op.alter_column('workout_day', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_workout_day_workout_id', table_name='workout_day')
    op.alter_column('workout_day_exercise', 'workout_day_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day_exercise', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day_exercise', 'exercise_type',
               existing_type=postgresql.ENUM('time_based', 'repetition_based', name='exercisetype'),
               nullable=True)
    op.alter_column('workout_day_exercise', 'sets',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_workout_day_exercise_exercise_id', table_name='workout_day_exercise')
    op.drop_index('ix_workout_day_exercise_workout_day_id', table_name='workout_day_exercise')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_workout_day_exercise_workout_day_id', 'workout_day_exercise', ['workout_day_id'], unique=False)
    op.create_index('ix_workout_day_exercise_exercise_id', 'workout_day_exercise', ['exercise_id'], unique=False)
    op.alter_column('workout_day_exercise', 'sets',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day_exercise', 'exercise_type',
               existing_type=postgresql.ENUM('time_based', 'repetition_based', name='exercisetype'),
               nullable=False)
    op.alter_column('workout_day_exercise', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day_exercise', 'workout_day_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('ix_workout_day_workout_id', 'workout_day', ['workout_id'], unique=False)
    op.alter_column('workout_day', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workout_day', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=True)
    op.alter_column('workout_day', 'day',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day', 'week',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day', 'day_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workout_day', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('role', 'status',
               existing_type=sa.Enum('active', 'inactive', name='rolestatus'),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.create_index('ix_exercise_equipment_exercise_id', 'exercise_equipment', ['exercise_id'], unique=False)
    op.drop_index(op.f('ix_member_workout_id'), table_name='member_workout')
    op.drop_table('member_workout')
    # ### end Alembic commands ###
