"""meal plan table changes

Revision ID: c876a37af894
Revises: ad5e939b994e
Create Date: 2024-07-29 18:48:56.420210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c876a37af894'
down_revision: Union[str, None] = 'ad5e939b994e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_time', sa.Enum('breakfast', 'breakfast_snack', 'lunch', 'lunch_snack', 'dinner', 'dinner_snack', name='mealtimeenum'), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_id'), 'meal', ['id'], unique=False)
    op.create_table('meal_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_img', sa.String(), nullable=True),
    sa.Column('visible_for', sa.Enum('only_myself', 'staff', 'members', 'everyone', name='visibleforenum'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plan_id'), 'meal_plan', ['id'], unique=False)
    # op.alter_column('workout', 'is_deleted',
    #            existing_type=sa.BOOLEAN(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('workout_day', 'is_deleted',
    #            existing_type=sa.BOOLEAN(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # op.alter_column('workout_day_exercise', 'is_deleted',
    #            existing_type=sa.BOOLEAN(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('workout_day_exercise', 'is_deleted',
    #            existing_type=sa.Integer(),
    #            type_=sa.BOOLEAN(),
    #            existing_nullable=True)
    # op.alter_column('workout_day', 'is_deleted',
    #            existing_type=sa.Integer(),
    #            type_=sa.BOOLEAN(),
    #            existing_nullable=True)
    # op.alter_column('workout', 'is_deleted',
    #            existing_type=sa.Integer(),
    #            type_=sa.BOOLEAN(),
    #            existing_nullable=True)
    op.drop_index(op.f('ix_meal_plan_id'), table_name='meal_plan')
    op.drop_table('meal_plan')
    op.drop_index(op.f('ix_meal_id'), table_name='meal')
    op.drop_table('meal')
    # ### end Alembic commands ###
