"""workout member assing to

Revision ID: cacbcd36c8c7
Revises: edc5dd14d2b7
Create Date: 2024-08-07 06:46:28.757361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cacbcd36c8c7'
down_revision: Union[str, None] = 'edc5dd14d2b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    client_status = sa.Enum('active', 'inactive', 'pending', name='client_status')
    client_status.create(op.get_bind(), checkfirst=True)
    #op.alter_column('client_organization', 'client_status',
    #           existing_type=postgresql.ENUM('active', 'inactive', 'pending', name='coach_status'),
    #           type_=sa.Enum('active', 'inactive', name='status'),
    #           existing_nullable=True)
    op.execute('ALTER TABLE client_organization ALTER COLUMN client_status TYPE client_status USING client_status::text::client_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
