"""Test v7

Revision ID: d3378231a5b6
Revises: 5765d4d376fe
Create Date: 2024-07-14 20:29:38.451138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3378231a5b6'
down_revision: Union[str, None] = '5765d4d376fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership_plan', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('membership_plan', sa.Column('status', sa.String(length=10), nullable=True))
    op.add_column('membership_plan', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('membership_plan', sa.Column('access_time', sa.JSON(), nullable=True))
    op.add_column('membership_plan', sa.Column('net_price', sa.Float(), nullable=True))
    op.add_column('membership_plan', sa.Column('income_category_id', sa.Integer(), nullable=True))
    op.add_column('membership_plan', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('membership_plan', sa.Column('total_price', sa.Float(), nullable=True))
    op.add_column('membership_plan', sa.Column('payment_method', sa.String(length=20), nullable=True))
    op.add_column('membership_plan', sa.Column('reg_fee', sa.Float(), nullable=True))
    op.add_column('membership_plan', sa.Column('billing_cycle', sa.String(length=30), nullable=True))
    op.add_column('membership_plan', sa.Column('auto_renewal', sa.Boolean(), nullable=True))
    op.add_column('membership_plan', sa.Column('renewal_details', sa.JSON(), nullable=True))
    op.add_column('membership_plan', sa.Column('credit_id', sa.Integer(), nullable=True))
    op.drop_column('membership_plan', 'price')
    op.drop_column('membership_plan', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membership_plan', sa.Column('created_at', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True))
    op.add_column('membership_plan', sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('membership_plan', 'credit_id')
    op.drop_column('membership_plan', 'renewal_details')
    op.drop_column('membership_plan', 'auto_renewal')
    op.drop_column('membership_plan', 'billing_cycle')
    op.drop_column('membership_plan', 'reg_fee')
    op.drop_column('membership_plan', 'payment_method')
    op.drop_column('membership_plan', 'total_price')
    op.drop_column('membership_plan', 'discount')
    op.drop_column('membership_plan', 'income_category_id')
    op.drop_column('membership_plan', 'net_price')
    op.drop_column('membership_plan', 'access_time')
    op.drop_column('membership_plan', 'description')
    op.drop_column('membership_plan', 'status')
    op.drop_column('membership_plan', 'group_id')
    # ### end Alembic commands ###
