"""user client country source entities changed

Revision ID: e1a0dbe9d14b
Revises: 70c9351dfca6
Create Date: 2024-06-26 18:52:39.305183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1a0dbe9d14b'
down_revision: Union[str, None] = '70c9351dfca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bank_account_id', table_name='bank_account')
    op.drop_table('bank_account')
    op.drop_index('ix_organization_users_email', table_name='organization_users')
    op.drop_index('ix_organization_users_id', table_name='organization_users')
    op.drop_index('ix_organization_users_org_id', table_name='organization_users')
    op.drop_table('organization_users')
    op.drop_index('ix_leads_id', table_name='leads')
    op.drop_table('leads')
    op.add_column('client', sa.Column('profile_img', sa.String(length=150), nullable=True))
    op.add_column('client', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('client', sa.Column('dob', sa.Date(), nullable=False))
    op.add_column('client', sa.Column('email_address', sa.String(), nullable=False))
    op.add_column('client', sa.Column('phone', sa.String(length=11), nullable=True))
    op.add_column('client', sa.Column('zipcode', sa.String(length=10), nullable=True))
    op.add_column('client', sa.Column('address_1', sa.String(length=100), nullable=True))
    op.add_column('client', sa.Column('address_2', sa.String(length=100), nullable=True))
    op.add_column('client', sa.Column('activated_on', sa.Date(), nullable=True))
    op.add_column('client', sa.Column('check_in', sa.DateTime(), nullable=True))
    op.add_column('client', sa.Column('last_online', sa.DateTime(), nullable=True))
    op.add_column('client', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('client', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('client', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('client', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.drop_constraint('client_email_key', 'client', type_='unique')
    op.create_unique_constraint(None, 'client', ['email_address'])
    op.drop_column('client', 'landline_number')
    op.drop_column('client', 'email')
    op.drop_column('client', 'address')
    op.drop_column('client', 'date_of_birth')
    op.drop_column('client', 'zip_code')
    op.drop_column('client', 'sex')
    op.drop_column('client', 'profile_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('profile_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('client', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('client', sa.Column('landline_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'client', type_='unique')
    op.create_unique_constraint('client_email_key', 'client', ['email'])
    op.drop_column('client', 'updated_by')
    op.drop_column('client', 'created_by')
    op.drop_column('client', 'updated_at')
    op.drop_column('client', 'created_at')
    op.drop_column('client', 'last_online')
    op.drop_column('client', 'check_in')
    op.drop_column('client', 'activated_on')
    op.drop_column('client', 'address_2')
    op.drop_column('client', 'address_1')
    op.drop_column('client', 'zipcode')
    op.drop_column('client', 'phone')
    op.drop_column('client', 'email_address')
    op.drop_column('client', 'dob')
    op.drop_column('client', 'gender')
    op.drop_column('client', 'profile_img')
    op.create_table('leads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mobile_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('home_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lead_owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lead_since', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='leads_pkey')
    )
    op.create_index('ix_leads_id', 'leads', ['id'], unique=False)
    op.create_table('organization_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='organization_users_pkey')
    )
    op.create_index('ix_organization_users_org_id', 'organization_users', ['org_id'], unique=False)
    op.create_index('ix_organization_users_id', 'organization_users', ['id'], unique=False)
    op.create_index('ix_organization_users_email', 'organization_users', ['email'], unique=True)
    op.create_table('bank_account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bank_account_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bic_swift_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bank_account_holder_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bank_account_pkey')
    )
    op.create_index('ix_bank_account_id', 'bank_account', ['id'], unique=False)
    # ### end Alembic commands ###
