"""Resolved enum errors in meal plan

Revision ID: e2ba705de480
Revises: adaaacffcfa2
Create Date: 2024-08-19 17:54:45.542550

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e2ba705de480'
down_revision: Union[str, None] = 'adaaacffcfa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

new_mealtime_enum = postgresql.ENUM(
    'Breakfast', 'Morning Snack', 'Lunch', 'Afternoon Snack', 'Dinner', 'Evening Snack',
    name='mealtimeenum'
)

def upgrade() -> None:
    op.execute("DROP TYPE IF EXISTS mealtimeenum cascade")
    new_mealtime_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('meal', sa.Column('meal_time', new_mealtime_enum, nullable=True))
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
