"""workout member assing to2

Revision ID: e555d6176d9d
Revises: cacbcd36c8c7
Create Date: 2024-08-07 08:26:50.606172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e555d6176d9d'
down_revision: Union[str, None] = 'cacbcd36c8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    client_status = sa.Enum('active', 'inactive', 'pending', name='clientstatus')
    client_status.create(op.get_bind(), checkfirst=True)
    #op.alter_column('client_organization', 'client_status',
    #           existing_type=postgresql.ENUM('active', 'inactive', 'pending', name='coach_status'),
    #           type_=sa.Enum('active', 'inactive', name='status'),
    #           existing_nullable=True)
    op.execute('ALTER TABLE client_organization ALTER COLUMN client_status TYPE clientstatus USING client_status::text::clientstatus')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end alembic commands ###
