"""updated intensity values

Revision ID: e6331b9cc6e6
Revises: 534c79be5447
Create Date: 2024-08-07 19:33:35.258240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6331b9cc6e6'
down_revision: Union[str, None] = '534c79be5447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE Intensity RENAME VALUE 'irm%' TO 'irm'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
