"""updated attributes of exercise model

Revision ID: e96726654f03
Revises: 081a37ffe3c4
Create Date: 2024-07-26 12:32:51.244822ggi
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e96726654f03'
down_revision: Union[str, None] = '081a37ffe3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipments', 'is_deleted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="is_deleted::boolean")
    op.alter_column('exercise', 'is_deleted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="is_deleted::boolean")
    op.alter_column('exercise_category', 'is_deleted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="is_deleted::boolean")
    op.alter_column('exercise_equipment', 'is_deleted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="is_deleted::boolean")
    op.alter_column('exercise_primary_joint', 'is_deleted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="is_deleted::boolean")
    op.alter_column('exercise_primary_muscle', 'is_deleted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="is_deleted::boolean")
    op.alter_column('exercise_secondary_muscle', 'is_deleted',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               postgresql_using="is_deleted::boolean")
    # op.alter_column('foods', 'category',
    #            existing_type=postgresql.ENUM('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='_categoryenum'),
    #            type_=sa.Enum('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='categoryenum'),
    #            existing_nullable=True)
    # op.alter_column('foods', 'weight_unit',
    #            existing_type=postgresql.ENUM('g', 'ml', 'g_ml', name='_weightunitenum'),
    #            type_=sa.Enum('g', 'ml', 'g_ml', name='weightunitenum'),
    #            existing_nullable=True)
    op.execute("ALTER TABLE foods ALTER COLUMN category TYPE _categoryenum USING category::_categoryenum")
    op.execute("ALTER TABLE foods ALTER COLUMN weight_unit TYPE _weightunitenum USING weight_unit::_weightunitenum")

    op.add_column('met', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('met', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('met', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # op.alter_column('muscle', 'is_deleted',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Boolean(),
    #            existing_nullable=True)
    op.execute("ALTER TABLE muscle ALTER COLUMN is_deleted TYPE BOOLEAN USING is_deleted::boolean")
    # op.alter_column('primary_joint', 'is_deleted',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Boolean(),
    #            existing_nullable=True)
    op.execute("ALTER TABLE primary_joint ALTER COLUMN is_deleted TYPE BOOLEAN USING is_deleted::boolean")
    # ### end Alembic commands ###


def downgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('primary_joint', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('muscle', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('met', 'is_deleted')
    op.drop_column('met', 'updated_by')
    op.drop_column('met', 'created_by')
    # op.alter_column('foods', 'weight_unit',
    #            existing_type=sa.Enum('g', 'ml', 'g_ml', name='weightunitenum'),
    #            type_=postgresql.ENUM('g', 'ml', 'g_ml', name='_weightunitenum'),
    #            existing_nullable=True)
    # op.alter_column('foods', 'category',
    #            existing_type=sa.Enum('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='categoryenum'),
    #            type_=postgresql.ENUM('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='_categoryenum'),
    #            existing_nullable=True)
    op.execute("ALTER TABLE foods ALTER COLUMN category TYPE categoryenum USING category::categoryenum")
    op.execute("ALTER TABLE foods ALTER COLUMN weight_unit TYPE weightunitenum USING weight_unit::weightunitenum")

    op.alter_column('exercise_secondary_muscle', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('exercise_primary_muscle', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('exercise_primary_joint', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('exercise_equipment', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('exercise_category', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('exercise', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('equipments', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
