"""resolved enum errors

Revision ID: edc5dd14d2b7
Revises: 0549a0c9f319
Create Date: 2024-08-06 14:46:59.074316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'edc5dd14d2b7'
down_revision: Union[str, None] = '0549a0c9f319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    status = sa.Enum('active', 'inactive',name="status")
    # status.create(op.get_bind())

    coach_status = sa.Enum('active', 'inactive','pending',name="coach_status")
    coach_status.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_organization', 'client_status',
               existing_type=sa.VARCHAR(length=100),
               type_=coach_status,
               existing_nullable=True,
               postgresql_using="client_status::coach_status")
    op.alter_column('coach_organization', 'coach_status',
               existing_type=sa.VARCHAR(),
               type_=coach_status,
               existing_nullable=True,
               postgresql_using="coach_status::coach_status")
    op.alter_column('exercise', 'exercise_intensity',
               existing_type=postgresql.ENUM('irm%', 'max_intensity', name='intensity'),
               nullable=True)
    op.alter_column('exercise', 'intensity_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    
    # Alter column with ENUM type
    op.alter_column('facility', 'status',
                    existing_type=sa.BOOLEAN(),
                    type_=status,
                    existing_nullable=False,
                    postgresql_using="status::text::status")
    
    op.alter_column('foods', 'category',
               existing_type=postgresql.ENUM('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='__categoryenum'),
               type_=sa.Enum('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='__categoryenum'),
               existing_nullable=True)
    op.alter_column('foods', 'weight_unit',
               existing_type=postgresql.ENUM('g', 'ml', 'g_ml', name='__weightunitenum'),
               type_=sa.Enum('g', 'ml', 'g_ml', name='__weightunitenum'),
               existing_nullable=True)
    op.add_column('income_category', sa.Column('status', sa.Enum('active', 'inactive', name='status'), nullable=True))
    op.alter_column('membership_plan', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=status,
               existing_nullable=True,
               postgresql_using='status::status')
    op.add_column('sale_tax', sa.Column('status', sa.Enum('active', 'inactive', name='status'), nullable=True))
    op.alter_column('staff', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=coach_status,
               existing_nullable=True,
               postgresql_using='status::coach_status')
    
    op.alter_column('workout', 'workout_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workout', 'visible_for',
               existing_type=postgresql.ENUM('only_myself', 'staff_of_my_club', 'members_of_my_club', 'everyone_in_my_club', name='visiblefor'),
               nullable=True)
    op.alter_column('workout', 'goals',
               existing_type=postgresql.ENUM('lose_weight', 'build_muscle', 'improved_well_being', 'improve_performance', 'rehabilitation', 'get_fit', 'shape_and_tone', name='workoutgoal'),
               nullable=True)
    op.alter_column('workout', 'level',
               existing_type=postgresql.ENUM('novice', 'beginner', 'intermediate', 'advanced', 'expert', name='workoutlevel'),
               nullable=True)
    op.alter_column('workout', 'weeks',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=True)
    op.alter_column('workout', 'update_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=True)
    op.alter_column('workout', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workout', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('workout', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('workout_day', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day', 'day_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workout_day', 'week',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day', 'day',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=True)
    op.alter_column('workout_day', 'update_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=True)
    op.alter_column('workout_day', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workout_day', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('workout_day_exercise', 'workout_day_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day_exercise', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day_exercise', 'exercise_type',
               existing_type=postgresql.ENUM('time_based', 'repetition_based', name='exercisetype'),
               nullable=True)
    op.alter_column('workout_day_exercise', 'sets',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day_exercise', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=True)
    op.alter_column('workout_day_exercise', 'update_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=True)
    op.alter_column('workout_day_exercise', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_day_exercise', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day_exercise', 'update_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=True)
    op.alter_column('workout_day_exercise', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=False)
    op.alter_column('workout_day_exercise', 'sets',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day_exercise', 'exercise_type',
               existing_type=postgresql.ENUM('time_based', 'repetition_based', name='exercisetype'),
               nullable=False)
    op.alter_column('workout_day_exercise', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day_exercise', 'workout_day_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('workout_day', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workout_day', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day', 'update_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=True)
    op.alter_column('workout_day', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=False)
    op.alter_column('workout_day', 'day',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day', 'week',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day', 'day_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workout_day', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('workout', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workout', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('workout', 'updated_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout', 'update_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=True)
    op.alter_column('workout', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               nullable=False)
    op.alter_column('workout', 'weeks',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout', 'level',
               existing_type=postgresql.ENUM('novice', 'beginner', 'intermediate', 'advanced', 'expert', name='workoutlevel'),
               nullable=False)
    op.alter_column('workout', 'goals',
               existing_type=postgresql.ENUM('lose_weight', 'build_muscle', 'improved_well_being', 'improve_performance', 'rehabilitation', 'get_fit', 'shape_and_tone', name='workoutgoal'),
               nullable=False)
    op.alter_column('workout', 'visible_for',
               existing_type=postgresql.ENUM('only_myself', 'staff_of_my_club', 'members_of_my_club', 'everyone_in_my_club', name='visiblefor'),
               nullable=False)
    op.alter_column('workout', 'workout_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('staff', 'status',
               existing_type=sa.Enum('active', 'inactive', 'pending', name='status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('sale_tax', 'status')
    op.alter_column('membership_plan', 'status',
               existing_type=sa.Enum('active', 'inactive', name='status'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('income_category', 'status')
    op.alter_column('foods', 'weight_unit',
               existing_type=sa.Enum('g', 'ml', 'g_ml', name='weightunitenum'),
               type_=postgresql.ENUM('g', 'ml', 'g_ml', name='__weightunitenum'),
               existing_nullable=True)
    op.alter_column('foods', 'category',
               existing_type=sa.Enum('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='categoryenum'),
               type_=postgresql.ENUM('baked_products', 'beverages', 'cheese_eggs', 'cooked_meals', 'fish_products', 'fruits_vegs', 'herbs_spices', 'meat_products', 'nuts_seeds_snacks', 'pasta_cereals', 'restaurant_meals', 'soups_sauces', 'sweets_candy', 'other', name='__categoryenum'),
               existing_nullable=True)
    op.alter_column('facility', 'status',
                    existing_type=sa.Enum('active', 'inactive', name='status'),
                    type_=sa.BOOLEAN(),
                    existing_nullable=False,
                    postgresql_using="status::text::boolean")
    
    op.alter_column('exercise', 'intensity_value',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('exercise', 'exercise_intensity',
               existing_type=postgresql.ENUM('irm%', 'max_intensity', name='intensity'),
               nullable=True)
    op.alter_column('coach_organization', 'coach_status',
               existing_type=sa.Enum('active', 'inactive', 'pending', name='status'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('client_organization', 'client_status',
               existing_type=sa.Enum('active', 'inactive','pending' ,name='status'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True
            )
    # ### end Alembic commands ###
