"""Test v9

Revision ID: ee5e343253ca
Revises: 3ebfc1a5ed4a
Create Date: 2024-06-27 14:35:16.783102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5e343253ca'
down_revision: Union[str, None] = '3ebfc1a5ed4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('lead_since', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.add_column('membership_plan', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('membership_plan', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('membership_plan', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('membership_plan', sa.Column('updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membership_plan', 'updated_by')
    op.drop_column('membership_plan', 'created_by')
    op.drop_column('membership_plan', 'updated_at')
    op.drop_column('membership_plan', 'created_at')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
