"""edit client

Revision ID: f0a7fb3f2910
Revises: e1a0dbe9d14b
Create Date: 2024-06-27 10:59:39.895362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a7fb3f2910'
down_revision: Union[str, None] = 'e1a0dbe9d14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_id', table_name='business')
    op.drop_table('business')
    op.add_column('client', sa.Column('source_id', sa.Integer(), nullable=True))
    op.add_column('client', sa.Column('country_id', sa.Integer(), nullable=True))
    op.drop_column('client', 'country')
    op.drop_column('client', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('client', 'country_id')
    op.drop_column('client', 'source_id')
    op.create_table('business',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='business_pkey'),
    sa.UniqueConstraint('email', name='business_email_key')
    )
    op.create_index('ix_business_id', 'business', ['id'], unique=False)
    # ### end Alembic commands ###
