"""update settings

Revision ID: f1c22f76115d
Revises: 5f82b3571275
Create Date: 2024-07-02 16:11:04.701829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c22f76115d'
down_revision: Union[str, None] = '5f82b3571275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('access', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.create_table('resource',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('parent', sa.String(length=50), nullable=True),
    sa.Column('is_parent', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_id'), 'resource', ['id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.add_column('staff', sa.Column('profile_img', sa.String(length=150), nullable=True))
    op.add_column('staff', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('staff', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('staff', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('staff', sa.Column('phone', sa.String(length=11), nullable=True))
    op.add_column('staff', sa.Column('mobile', sa.String(length=11), nullable=True))
    op.add_column('staff', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('source_id', sa.Integer(), nullable=True))
    op.add_column('staff', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('staff', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('staff', sa.Column('city', sa.String(length=20), nullable=True))
    op.add_column('staff', sa.Column('zipcode', sa.String(), nullable=True))
    op.add_column('staff', sa.Column('address_1', sa.String(length=100), nullable=True))
    op.add_column('staff', sa.Column('address_2', sa.String(), nullable=True))
    op.drop_index('ix_staff_org_id', table_name='staff')
    op.drop_column('staff', 'name')
    op.drop_column('staff', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('staff', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_staff_org_id', 'staff', ['org_id'], unique=False)
    op.drop_column('staff', 'address_2')
    op.drop_column('staff', 'address_1')
    op.drop_column('staff', 'zipcode')
    op.drop_column('staff', 'city')
    op.drop_column('staff', 'country_id')
    op.drop_column('staff', 'role_id')
    op.drop_column('staff', 'source_id')
    op.drop_column('staff', 'notes')
    op.drop_column('staff', 'mobile')
    op.drop_column('staff', 'phone')
    op.drop_column('staff', 'dob')
    op.drop_column('staff', 'last_name')
    op.drop_column('staff', 'first_name')
    op.drop_column('staff', 'profile_img')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_resource_id'), table_name='resource')
    op.drop_table('resource')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_table('permission')
    # ### end Alembic commands ###
