"""User Col Remove Test Migrate

Revision ID: f4405084a5e4
Revises: 2d9017944091
Create Date: 2024-06-26 13:13:50.544417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4405084a5e4'
down_revision: Union[str, None] = '2d9017944091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_id', table_name='client')
    op.drop_table('client')
    op.drop_index('ix_coach_id', table_name='coach')
    op.drop_table('coach')
    op.drop_index('ix_business_id', table_name='business')
    op.drop_table('business')
    op.drop_index('ix_leads_id', table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_client_organization_id', table_name='client_organization')
    op.drop_table('client_organization')
    op.drop_index('ix_client_membership_id', table_name='client_membership')
    op.drop_table('client_membership')
    op.drop_index('ix_membership_plan_id', table_name='membership_plan')
    op.drop_table('membership_plan')
    op.drop_index('ix_client_coach_id', table_name='client_coach')
    op.drop_table('client_coach')
    op.drop_index('ix_user_membership_id', table_name='user_membership')
    op.drop_table('user_membership')
    op.drop_index('ix_coach_organization_id', table_name='coach_organization')
    op.drop_table('coach_organization')
    op.drop_index('ix_bank_account_id', table_name='bank_account')
    op.drop_table('bank_account')
    op.drop_index('ix_organization_id', table_name='organization')
    op.drop_table('organization')
    op.drop_index('ix_organization_users_email', table_name='organization_users')
    op.drop_index('ix_organization_users_id', table_name='organization_users')
    op.drop_index('ix_organization_users_org_id', table_name='organization_users')
    op.drop_table('organization_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='organization_users_pkey')
    )
    op.create_index('ix_organization_users_org_id', 'organization_users', ['org_id'], unique=False)
    op.create_index('ix_organization_users_id', 'organization_users', ['id'], unique=False)
    op.create_index('ix_organization_users_email', 'organization_users', ['email'], unique=True)
    op.create_table('organization',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='organization_pkey')
    )
    op.create_index('ix_organization_id', 'organization', ['id'], unique=False)
    op.create_table('bank_account',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bank_account_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bic_swift_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bank_account_holder_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bank_account_pkey')
    )
    op.create_index('ix_bank_account_id', 'bank_account', ['id'], unique=False)
    op.create_table('coach_organization',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='coach_organization_pkey')
    )
    op.create_index('ix_coach_organization_id', 'coach_organization', ['id'], unique=False)
    op.create_table('user_membership',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('membership_plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_membership_pkey')
    )
    op.create_index('ix_user_membership_id', 'user_membership', ['id'], unique=False)
    op.create_table('client_coach',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='client_coach_pkey')
    )
    op.create_index('ix_client_coach_id', 'client_coach', ['id'], unique=False)
    op.create_table('membership_plan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='membership_plan_pkey')
    )
    op.create_index('ix_membership_plan_id', 'membership_plan', ['id'], unique=False)
    op.create_table('client_membership',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('membership_plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='client_membership_pkey')
    )
    op.create_index('ix_client_membership_id', 'client_membership', ['id'], unique=False)
    op.create_table('client_organization',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='client_organization_pkey')
    )
    op.create_index('ix_client_organization_id', 'client_organization', ['id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mobile_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('home_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lead_owner', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lead_since', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='leads_pkey')
    )
    op.create_index('ix_leads_id', 'leads', ['id'], unique=False)
    op.create_table('business',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='business_pkey'),
    sa.UniqueConstraint('email', name='business_email_key')
    )
    op.create_index('ix_business_id', 'business', ['id'], unique=False)
    op.create_table('coach',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('coach_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='coach_pkey')
    )
    op.create_index('ix_coach_id', 'coach', ['id'], unique=False)
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('wallet_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('profile_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('own_member_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('landline_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mobile_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('client_since', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_business', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='client_pkey'),
    sa.UniqueConstraint('email_address', name='client_email_address_key')
    )
    op.create_index('ix_client_id', 'client', ['id'], unique=False)
    # ### end Alembic commands ###
