"""update: role status type cast

Revision ID: fbfc14cfa578
Revises: 0cd942ed5af0
Create Date: 2024-07-23 16:23:22.308523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbfc14cfa578'
down_revision: Union[str, None] = '0cd942ed5af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('role', 'status',
    #            existing_type=sa.VARCHAR(length=50),
    #            type_=sa.Boolean(),
    #            existing_nullable=True)
    op.execute("ALTER TABLE role ALTER COLUMN status TYPE BOOLEAN USING status::boolean")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('role', 'status',
    #            existing_type=sa.Boolean(),
    #            type_=sa.VARCHAR(length=50),
    #            existing_nullable=True)
    op.execute("ALTER TABLE role ALTER COLUMN status TYPE VARCHAR(50) USING status::varchar")
    # ### end Alembic commands ###
