"""MealPlan table changes

Revision ID: fc212dd9ccab
Revises: 459713a4043e
Create Date: 2024-07-31 18:26:08.349736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc212dd9ccab'
down_revision: Union[str, None] = '459713a4043e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_meal_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('meal_plan_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_meal_plan_id'), 'member_meal_plan', ['id'], unique=False)
    op.add_column('meal_plan', sa.Column('persona', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plan', 'persona')
    op.drop_index(op.f('ix_member_meal_plan_id'), table_name='member_meal_plan')
    op.drop_table('member_meal_plan')
    # ### end Alembic commands ###
