"""updated workout table

Revision ID: fc291c325f91
Revises: 9167b08b6f89
Create Date: 2024-08-23 17:58:49.931417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc291c325f91'
down_revision: Union[str, None] = '9167b08b6f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS exerciseintensity cascade;")

    op.alter_column('member_workout', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('member_workout', 'update_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('workout', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('workout', 'update_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('workout_day', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('workout_day', 'update_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('workout_day_exercise', sa.Column('intensity_value', sa.Float(), nullable=True))
    op.add_column(
        'workout_day_exercise',
        sa.Column('intensity_type', sa.Enum('irm', 'max_intensity', name='intensity'), nullable=True)
    )
    op.alter_column('workout_day_exercise', 'create_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('workout_day_exercise', 'update_user_type',
               existing_type=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('workout_day_exercise', 'percentage_of_1rm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_day_exercise', sa.Column('percentage_of_1rm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('workout_day_exercise', 'update_user_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               existing_nullable=True)
    op.alter_column('workout_day_exercise', 'create_user_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               existing_nullable=False)
    op.alter_column('workout_day_exercise', 'intensity_type',
               existing_type=sa.Enum('irm', 'max_intensity', name='intensity'),
               type_=postgresql.ENUM('max', 'percentage_of_1rm', name='exerciseintensity'),
               existing_nullable=False)
    op.drop_column('workout_day_exercise', 'intensity_value')
    op.alter_column('workout_day', 'update_user_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               existing_nullable=True)
    op.alter_column('workout_day', 'create_user_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               existing_nullable=False)
    op.alter_column('workout', 'update_user_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               existing_nullable=True)
    op.alter_column('workout', 'create_user_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               existing_nullable=False)
    op.alter_column('member_workout', 'update_user_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               existing_nullable=True)
    op.alter_column('member_workout', 'create_user_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('staff', 'member', 'coach', name='usertype'),
               existing_nullable=False)
    # ### end Alembic commands ###
